use UNIVER;
SELECT 
  PROFESSION.PROFESSION_NAME, 
  SUBJECT.SUBJECT_NAME, 
  AVG(PROGRESS.NOTE) AS AVERAGE_NOTE
FROM 
  [GROUP]
  JOIN PROFESSION ON [GROUP].PROFESSION = PROFESSION.PROFESSION 
  JOIN STUDENT ON [GROUP].IDGROUP = STUDENT.IDGROUP 
  JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT 
  JOIN SUBJECT ON PROGRESS.SUBJECT = SUBJECT.SUBJECT 
WHERE 
  [GROUP].FACULTY = '“Œ¬'
GROUP BY 
  PROFESSION.PROFESSION_NAME, 
  SUBJECT.SUBJECT_NAME

EXCEPT

SELECT 
  PROFESSION.PROFESSION_NAME, 
  SUBJECT.SUBJECT_NAME,  
  AVG(PROGRESS.NOTE) AS AVERAGE_NOTE
FROM 
  [GROUP]
  JOIN PROFESSION ON [GROUP].PROFESSION = PROFESSION.PROFESSION 
  JOIN STUDENT ON [GROUP].IDGROUP = STUDENT.IDGROUP 
  JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT 
  JOIN SUBJECT ON PROGRESS.SUBJECT = SUBJECT.SUBJECT 
WHERE 
  [GROUP].FACULTY = '’“Ë“'
GROUP BY 
  PROFESSION.PROFESSION_NAME, 
  SUBJECT.SUBJECT_NAME;
