USE UNIVER;
SELECT 
  FACULTY.FACULTY_NAME, 
  PROFESSION.PROFESSION_NAME, 
  SUBJECT.SUBJECT_NAME, 
  AVG(PROGRESS.NOTE) AS AVERAGE_NOTE
FROM 
  FACULTY
  JOIN [GROUP] ON FACULTY.FACULTY = [GROUP].FACULTY 
  JOIN PROFESSION ON [GROUP].PROFESSION = PROFESSION.PROFESSION 
  JOIN STUDENT ON [GROUP].IDGROUP = STUDENT.IDGROUP 
  JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT 
  JOIN SUBJECT ON PROGRESS.SUBJECT = SUBJECT.SUBJECT 
WHERE 
  FACULTY.FACULTY = 'ÒÎÂ'
GROUP BY 
  FACULTY.FACULTY_NAME, 
  PROFESSION.PROFESSION_NAME, 
  SUBJECT.SUBJECT_NAME 
WITH CUBE;
