use UNIVER;
SELECT 
  [GROUP].FACULTY, 
  [GROUP].PROFESSION, 
  SUBJECT.SUBJECT_NAME, 
  AVG(PROGRESS.NOTE) AS AVERAGE_NOTE
FROM 
  [GROUP]
  JOIN STUDENT ON [GROUP].IDGROUP = STUDENT.IDGROUP 
  JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT 
  JOIN SUBJECT ON PROGRESS.SUBJECT = SUBJECT.SUBJECT 
WHERE 
  [GROUP].FACULTY = 'ТОВ'
GROUP BY 
  [GROUP].FACULTY, 
  [GROUP].PROFESSION, 
  SUBJECT.SUBJECT_NAME;





  SELECT 
  [GROUP].FACULTY, 
  [GROUP].PROFESSION, 
  SUBJECT.SUBJECT_NAME, 
  AVG(PROGRESS.NOTE) AS AVERAGE_NOTE
FROM 
  [GROUP]
  JOIN STUDENT ON [GROUP].IDGROUP = STUDENT.IDGROUP 
  JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT 
  JOIN SUBJECT ON PROGRESS.SUBJECT = SUBJECT.SUBJECT 
WHERE 
  [GROUP].FACULTY = 'ХТиТ'
GROUP BY 
  [GROUP].FACULTY, 
  [GROUP].PROFESSION, 
  SUBJECT.SUBJECT_NAME;



  SELECT * FROM (
  -- Запрос для факультета ТОВ
  SELECT 
    [GROUP].FACULTY, 
    [GROUP].PROFESSION, 
    SUBJECT.SUBJECT_NAME, 
    AVG(PROGRESS.NOTE) AS AVERAGE_NOTE
  FROM 
    [GROUP]
    JOIN STUDENT ON [GROUP].IDGROUP = STUDENT.IDGROUP 
    JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT 
    JOIN SUBJECT ON PROGRESS.SUBJECT = SUBJECT.SUBJECT 
  WHERE 
    [GROUP].FACULTY = 'ТОВ'
  GROUP BY 
    [GROUP].FACULTY, 
    [GROUP].PROFESSION, 
    SUBJECT.SUBJECT_NAME
  UNION ALL
  -- Запрос для факультета ХТиТ
  SELECT 
    [GROUP].FACULTY, 
    [GROUP].PROFESSION, 
    SUBJECT.SUBJECT_NAME, 
    AVG(PROGRESS.NOTE) AS AVERAGE_NOTE
  FROM 
    [GROUP]
    JOIN STUDENT ON [GROUP].IDGROUP = STUDENT.IDGROUP 
    JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT 
    JOIN SUBJECT ON PROGRESS.SUBJECT = SUBJECT.SUBJECT 
  WHERE 
    [GROUP].FACULTY = 'ТОВ'
  GROUP BY 
    [GROUP].FACULTY, 
    [GROUP].PROFESSION, 
    SUBJECT.SUBJECT_NAME
) AS combined_results;



  SELECT * FROM (
  -- Запрос для факультета ТОВ
  SELECT 
    [GROUP].FACULTY, 
    [GROUP].PROFESSION, 
    SUBJECT.SUBJECT_NAME, 
    AVG(PROGRESS.NOTE) AS AVERAGE_NOTE
  FROM 
    [GROUP]
    JOIN STUDENT ON [GROUP].IDGROUP = STUDENT.IDGROUP 
    JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT 
    JOIN SUBJECT ON PROGRESS.SUBJECT = SUBJECT.SUBJECT 
  WHERE 
    [GROUP].FACULTY = 'ТОВ'
  GROUP BY 
    [GROUP].FACULTY, 
    [GROUP].PROFESSION, 
    SUBJECT.SUBJECT_NAME
  UNION
  -- Запрос для факультета ХТиТ
  SELECT 
    [GROUP].FACULTY, 
    [GROUP].PROFESSION, 
    SUBJECT.SUBJECT_NAME, 
    AVG(PROGRESS.NOTE) AS AVERAGE_NOTE
  FROM 
    [GROUP]
    JOIN STUDENT ON [GROUP].IDGROUP = STUDENT.IDGROUP 
    JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT 
    JOIN SUBJECT ON PROGRESS.SUBJECT = SUBJECT.SUBJECT 
  WHERE 
    [GROUP].FACULTY = 'ТОВ'
  GROUP BY 
    [GROUP].FACULTY, 
    [GROUP].PROFESSION, 
    SUBJECT.SUBJECT_NAME
) AS combined_results;




-- Запрос для получения пересечения двух множеств строк
SELECT 
  PROFESSION.PROFESSION_NAME, 
  SUBJECT.SUBJECT_NAME, 
  AVG(PROGRESS.NOTE) AS AVERAGE_NOTE
FROM 
  [GROUP]
  JOIN PROFESSION ON [GROUP].PROFESSION = PROFESSION.PROFESSION 
  JOIN STUDENT ON [GROUP].IDGROUP = STUDENT.IDGROUP 
  JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT 
  JOIN SUBJECT ON PROGRESS.SUBJECT = SUBJECT.SUBJECT 
WHERE 
  [GROUP].FACULTY = 'ТОВ'
GROUP BY 
  PROFESSION.PROFESSION_NAME, 
  SUBJECT.SUBJECT_NAME

INTERSECT

SELECT 
  PROFESSION.PROFESSION_NAME, 
  SUBJECT.SUBJECT_NAME, 
  AVG(PROGRESS.NOTE) AS AVERAGE_NOTE
FROM 
  [GROUP]
  JOIN PROFESSION ON [GROUP].PROFESSION = PROFESSION.PROFESSION 
  JOIN STUDENT ON [GROUP].IDGROUP = STUDENT.IDGROUP 
  JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT 
  JOIN SUBJECT ON PROGRESS.SUBJECT = SUBJECT.SUBJECT 
WHERE 
  [GROUP].FACULTY = 'ХТиТ'
GROUP BY 
  PROFESSION.PROFESSION_NAME, 
  SUBJECT.SUBJECT_NAME;