use UNIVER;
SELECT PULPIT.PULPIT_NAME, FACULTY.FACULTY_NAME
FROM PULPIT
FULL OUTER JOIN FACULTY ON PULPIT.FACULTY = FACULTY.FACULTY_NAME
WHERE FACULTY.FACULTY_NAME IS NULL


SELECT PULPIT.PULPIT_NAME, FACULTY.FACULTY_NAME
FROM PULPIT
FULL OUTER JOIN FACULTY ON PULPIT.FACULTY = FACULTY.FACULTY_NAME
WHERE PULPIT.PULPIT_NAME IS NULL


SELECT *
FROM STUDENT
FULL OUTER JOIN [GROUP] ON STUDENT.IDGROUP = [GROUP].IDGROUP
