USE UNIVER;

-- 1

INSERT INTO PROGRESS (SUBJECT, IDSTUDENT, PDATE, NOTE)
VALUES
    ('ад', 300, '2023-04-16', 3),
    ('нюХо', 301, '2023-04-15', 2),
    ('дд', 302, '2023-04-14', 3);

SELECT * FROM PROGRESS;

DECLARE @IDSTUDENT INT, @NOTE INT;

DECLARE cursor_progress CURSOR FOR
SELECT p.IDSTUDENT, p.NOTE
FROM PROGRESS p
INNER JOIN STUDENT s ON s.IDSTUDENT = p.IDSTUDENT
INNER JOIN [GROUP] g ON g.IDGROUP = s.IDGROUP
WHERE p.NOTE < 4;

OPEN cursor_progress;

FETCH NEXT FROM cursor_progress INTO @IDSTUDENT, @NOTE;

WHILE @@FETCH_STATUS = 0
BEGIN
    DELETE FROM PROGRESS WHERE IDSTUDENT = @IDSTUDENT AND NOTE = @NOTE;
    FETCH NEXT FROM cursor_progress INTO @IDSTUDENT, @NOTE;
END;

CLOSE cursor_progress;
DEALLOCATE cursor_progress;

-- 2

INSERT INTO STUDENT (IDSTUDENT, IDGROUP, NAME)
VALUES
(4, 22, 'Ivanov Ivan'),
(5, 23, 'Petrov Petr'),
(6, 26, 'Sidorov Sidr');


INSERT INTO PROGRESS (SUBJECT, IDSTUDENT, PDATE, NOTE)
VALUES
    ('ад', 1, '2023-04-16', 3);

SELECT * FROM PROGRESS;

DECLARE @IDSTUDENT INT, @NOTE INT;

SET @IDSTUDENT = 4;

DECLARE cursor_progress CURSOR FOR
SELECT NOTE
FROM PROGRESS
WHERE IDSTUDENT = @IDSTUDENT;

OPEN cursor_progress;

FETCH NEXT FROM cursor_progress INTO @NOTE;

WHILE @@FETCH_STATUS = 0
BEGIN
    UPDATE PROGRESS SET NOTE = @NOTE + 1 WHERE IDSTUDENT = @IDSTUDENT AND NOTE = @NOTE;
    FETCH NEXT FROM cursor_progress INTO @NOTE;
END;

CLOSE cursor_progress;
DEALLOCATE cursor_progress;

