use UNIVER;
SELECT 
    IDSTUDENT,
    AVG(CASE WHEN SUBJECT = 'нюХо' THEN NOTE END) AS AVG_OAIP,
    AVG(CASE WHEN SUBJECT = 'ад' THEN NOTE END) AS AVG_BD,
    AVG(CASE WHEN SUBJECT = 'ясад' THEN NOTE END) AS AVG_SUBD
FROM PROGRESS
GROUP BY IDSTUDENT
