use UNIVER;
SELECT * FROM STUDENT
WHERE IDGROUP = ALL (SELECT IDGROUP FROM [GROUP] WHERE YEAR_FIRST = '2014')


SELECT * FROM STUDENT
WHERE IDGROUP = ANY (SELECT IDGROUP FROM [GROUP] WHERE YEAR_FIRST = '2012')
