use UNIVER;
SELECT 
    AUDITORIUM_TYPE.AUDITORIUM_TYPENAME, 
    MIN(AUDITORIUM.AUDITORIUM_CAPACITY) AS MIN_CAPACITY, 
    MAX(AUDITORIUM.AUDITORIUM_CAPACITY) AS MAX_CAPACITY, 
    AVG(AUDITORIUM.AUDITORIUM_CAPACITY) AS AVG_CAPACITY, 
    SUM(AUDITORIUM.AUDITORIUM_CAPACITY) AS TOTAL_CAPACITY, 
    COUNT(AUDITORIUM.AUDITORIUM_TYPE) AS NUM_AUDITORIUMS 
FROM 
    AUDITORIUM 
    JOIN AUDITORIUM_TYPE ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE 
GROUP BY 
    AUDITORIUM_TYPE.AUDITORIUM_TYPENAME;
