use UNIVER;
SELECT 
  SUBJECT.SUBJECT_NAME, 
  COUNT(CASE WHEN PROGRESS.NOTE IN (8, 9) THEN 1 END) AS COUNT_GOOD_GRADES
FROM 
  PROGRESS 
  INNER JOIN SUBJECT ON PROGRESS.SUBJECT = SUBJECT.SUBJECT
GROUP BY 
  SUBJECT.SUBJECT_NAME
HAVING 
  COUNT(CASE WHEN PROGRESS.NOTE IN (8, 9) THEN 1 END) > 0
ORDER BY 
  COUNT_GOOD_GRADES DESC;
