use UNIVER;
SELECT 
  f.FACULTY_NAME AS FACULTY_NAME, 
  p.PROFESSION_NAME AS PROFESSION_NAME, 
  g.YEAR_FIRST AS YEAR_FIRST, 
  pr.SUBJECT,
  ROUND(AVG(CAST(pr.NOTE AS FLOAT)), 2) AS AVG_GRADE
FROM 
  FACULTY f
  INNER JOIN [GROUP] g ON f.FACULTY = g.FACULTY 
  INNER JOIN STUDENT s ON g.IDGROUP = s.IDGROUP 
  INNER JOIN PROGRESS pr ON s.IDSTUDENT = pr.IDSTUDENT 
                       AND pr.NOTE IS NOT NULL 
  INNER JOIN PROFESSION p ON g.PROFESSION = p.PROFESSION
WHERE 
  pr.SUBJECT = '¡ƒ' OR pr.SUBJECT = 'Œ¿Ëœ'
GROUP BY 
  f.FACULTY_NAME, 
  p.PROFESSION_NAME, 
  g.YEAR_FIRST,
  pr.SUBJECT
ORDER BY 
  AVG_GRADE DESC;
