use UNIVER;
SELECT 
  PROFESSION.PROFESSION_NAME, 
  SUBJECT.SUBJECT_NAME, 
  FACULTY.FACULTY,
  ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT)), 2) AS AVG_GRADE
FROM 
  FACULTY 
  INNER JOIN [GROUP] ON FACULTY.FACULTY = [GROUP].FACULTY 
  INNER JOIN STUDENT ON [GROUP].IDGROUP = STUDENT.IDGROUP 
  INNER JOIN PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT 
                       AND PROGRESS.NOTE IS NOT NULL 
  INNER JOIN SUBJECT ON PROGRESS.SUBJECT = SUBJECT.SUBJECT 
  INNER JOIN PROFESSION ON [GROUP].PROFESSION = PROFESSION.PROFESSION 
                         AND PROFESSION.FACULTY = FACULTY.FACULTY
WHERE 
  FACULTY.FACULTY = 'ÒÎÂ'
GROUP BY 
  PROFESSION.PROFESSION_NAME, 
  FACULTY.FACULTY,
  SUBJECT.SUBJECT_NAME;
