use UNIVER;

IF (SELECT SUM(AUDITORIUM_CAPACITY) FROM AUDITORIUM) > 600
BEGIN
    PRINT 'Вместимость аудиторий больше 200.';
	SELECT 
    COUNT(*) AS [Number of Auditoriums], 
    AVG(AUDITORIUM_CAPACITY) AS [Average Capacity], 
    (SELECT COUNT(*) FROM AUDITORIUM WHERE AUDITORIUM_CAPACITY < (SELECT AVG(AUDITORIUM_CAPACITY) FROM AUDITORIUM)) AS [Number of Small Auditoriums], 
    CONVERT(DECIMAL(5,2), (SELECT COUNT(*) FROM AUDITORIUM WHERE AUDITORIUM_CAPACITY < (SELECT AVG(AUDITORIUM_CAPACITY) FROM AUDITORIUM)) * 100.0 / COUNT(*)) AS [Percentage of Small Auditoriums]
	FROM AUDITORIUM;
END
ELSE
BEGIN
    PRINT 'Вместимость аудиторий меньше 200.';
	SELECT 
	SUM(AUDITORIUM_CAPACITY) AS [Max Capacity]
	FROM AUDITORIUM;
END
